import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto my-10 max-w-2xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold"> Shopping List</h2>
          <Link
            className="rounded-md bg-violet-500 p-3 transition hover:bg-violet-50"
            href="/addItem"
          >
            Add Shopping Item
          </Link>
        </div>
      </main>
    </>
  );
};

export default Home;
